config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
  get 'about', to:'pages#about'
  resources :articals 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artical.rb
class Artical < ApplicationRecord
  validates :title, :presence => true ,:length => { :minimum => 6 }
  validates :discription, :presence => true , :length => { :minimum => 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articals_controller.rb
class ArticalsController < ApplicationController
  before_action :set_artical, only: [:show, :edit, :update, :destroy ]

  def show 
  end

  def index 
    @articals = Artical.all.order(created_at: :desc)
  end

  def new
    @artical = Artical.new
  end

  def create
    @artical = Artical.new(artical_params)
    if @artical.save
      flash[:notice] = "Article was successfully Created."
     redirect_to artical_path(@artical)
    else 
      render 'new'
    end
  end

  def edit 
  end

  def update 
    if @artical.update(artical_params)
      flash[:notice] = "Article was successfully updated "
      redirect_to @artical
    else
      render "edit"
    end

  end

  def destroy
    @artical.destroy
      flash[:success] = 'Article was successfully deleted.'
      redirect_to articals_path
    
  end

  private

  def set_artical
    @artical = Artical.find(params[:id])
  end

  def artical_params 
    params.require(:artical).permit(:title , :discription)
  end
  
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articals_helper.rb
module ArticalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/articals/_form.html.erb
<%= form_with(model: @artical , local: true ) do |f| %>
  <div class="container shadow p-5 mb-5 bg-body rounded">
    <%= render 'shaerd/errors' %>
    <form>
      <div class="mb-3">
        <%= f.label :title , class:"form-label" %><br>
        <%= f.text_field :title , class:"form-control" , placeholder:"Ttile of Article"%>
      </div>
      <div class="mb-3">
        <%= f.label :description, class:"form-label" %><br>
        <%= f.text_area :discription , class:"form-control" , placeholder:"Description of Article" , size: "10x5"%>
      </div>
      <div class="d-grid gap-2 col-6 mx-auto">
       <%= f.submit class:"btn btn-primary"%>
      </div>
    </form>
 </div>
<% end %>

app/views/articals/edit.html.erb
<h1 class="artical-list"> Edit  Artical </h1>

<%= render 'form'%>
<div class="container mt-3">
 <a><%= link_to "Back to articals" , articals_path , class:"btn btn-warning" %></a>
</div> 

app/views/articals/index.html.erb
<h1 class="artical-list">Listing all articles</h1>


<div class="row justify-content-md-center">
<div class="col-8">
<% @articals.each do |artical|%>
<div class="container-md">
  <div class="card text-center" id="shedo">
    <div class="card-header bg-info text-white">
      <em>By Gopal Patidar</em>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= link_to artical.title.capitalize , artical_path(artical) , class:"text-success"%></h5>
      <p class="card-text"><%= truncate(artical.discription, length: 100)%></p>
      <p><%= link_to"Show" , artical_path(artical) , class:"btn btn-outline-success"%>
      <%= link_to"Edit" , edit_artical_path(artical) , class:"btn btn-outline-info"%>
      <%= button_to"Delete" , artical_path(artical) , method: :delete ,  data:  {turbo_confirm: "Are you sure?"} , class:"btn btn-outline-danger"%>
      </p>
    </div>
    <div class="card-footer text-muted">
      <small> Created <%= time_ago_in_words(artical.created_at)%> ago </small>
    </div>
  </div>
</div>  
<% end %>  

app/views/articals/new.html.erb
<h1 class="artical-list"> Create New Article </h1>

<%= render 'form'%>
<p class="container mt-3">
<a><%= link_to "Back to Articals" , articals_path , class:"btn btn-warning"%></a>
</p>

app/views/articals/show.html.erb
<h2 class="artical-list"><%=  @artical.title.capitalize %></h2>

<div class="row justify-content-md-center">
<div class="col-8">
<div class="container-md">
  <div class="card text-center" id="shedo">
    <div class="card-header bg-info text-white">
      <em>By Gopal Patidar</em>
    </div>
    <div class="card-body">
      <div class="card-text text-left"><%= simple_format(@artical.discription.capitalize)%></div>
      <p><%= link_to"Edit" , edit_artical_path(@artical) , class:"btn btn-outline-info"%>
      <%= button_to"Delete" , artical_path(@artical) , method: :delete ,  data:  {turbo_confirm: "Are you sure?"} , class:"btn btn-outline-danger"%>
    </div>
    <div class="card-footer text-muted">
      <small> Created <%= time_ago_in_words(@artical.created_at)%> ago </small>
    </div>
  </div>
</div>  
<%= link_to "Backe to Articals" , articals_path , class: "btn btn-primary"%></a></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name , msg|%>
<div class="container mt-2" >
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
 </div> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'pages/header'%>
    <%= render 'layouts/messages'%>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/pages/_header.html.erb
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid">
        <%= link_to "ALPHA BLOG" , root_path , class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            
            <li class="nav-item">
             <%= link_to "About" , about_path, class: "nav-link active"%>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link active dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Article
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Create new Article" , new_artical_path , class:"dropdown-item" %></li>
                <li><%= link_to " Articles" , articals_path , class:"dropdown-item" %></li>                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled">Disabled</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/pages/about.html.erb
<h1> Welcome to about page</h1>
<a><%= link_to " Articals" , articals_path %></a>
<a><%= link_to "Home" , root_path %></a>

app/views/pages/home.html.erb
<link href="assets/css/mean.css" rel="stylesheet" />


<div class="container-md">
<div class="card text-center">
  
  <div class="card-body" id="bgi">
    <h5 class="card-title text-white" id="bgi-title">Alpha Blog</h5>
    <p class="card-text text-white" id="bgi-text">f the Arial font were not found on the end user's computer, the browser would display a default font. If you are concerned that the font.</p>
    <p class="card-text text-white">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-success btn-lg">Sign Up!</a>
  </div>
  
</div>
</div>

app/views/shaerd/_errors.html.erb
<% if @artical.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <h4 class="alert-heading">not correct chake!</h4>
      <ul>
        <% @artical.errors.full_messages.each do |msg|%>
          <li><%= msg %></li>
        <% end %>
      </ul>
   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>